### PR TITLE
Create a bootable ISO for BIOS and UEFI

### PR DESCRIPTION
**Pull request by Lorgne**
As documented on [Fedora Wiki](https://fedoraproject.org/wiki/User:Pjones/BootableCDsForBIOSAndUEFI).

### CODE REVIEW

**Comment by phillxnet** [comment]
@Lorgne Thanks for the pull request, it would be great to have this one sorted.

Quick question; have your built and tested the resulting iso for uefi boot / install. I'm afraid I'm not very familiar with this procedure myself  and haven't put the time in yet so this is another one for @schakrava 's. If you have built and tested the iso what procedure did you follow to confirm all was as expected. This way I and others can test as well and help with this one getting merged.

Linking to the associated issue #5

**Comment by Lorgne** [comment]
I wanted to install Rockstor on a type 2 Hyper-V virtual machine. And this
type of VM is only able to boot on an UEFI compatible ISO. I extracted the
files of the non UEFI ISO in a folder, used mkisofs with the new parameters
and added the md5. With the corrected ISO, installation was successful.

(Default language had to be US English because some of the Python code
crashes if dates aren't in this locale format. Btrfs partitionning had to
be manually selected because the installer defaults to LVM. At first, the
web interface wasn't reachable, but I think it was a delay before it was
really online after the first reboot.)

Basic manipulation of the web interface seems to work (adding disks, pool
creation,...). I blocked on creating an SMB share with an exception about
Samba daemon not able to access a conf file.

**Comment by schakrava** [comment]
This is very useful @Lorgne. I plan to test it in the next few days and hopefully merge it for the upcoming 3.8-13.

**Comment by dbgunsolus** [comment]
@Lorgne can you give me the exact steps you used to create the ISO? I followed the wiki [here](https://fedoraproject.org/wiki/User:Pjones/BootableCDsForBIOSAndUEFI) for the hybrid UEFI/BIOS Method, and was able to build the iso successfully. However, when I try to boot to it, it gets hung on Mounted configuration File System, and then I get dracut says that it could not boot, that /dev/root does not exist.
Nvm, still new to github, saw where I can click on what procedure you followed, thanks @Lorgne 
Followed, your procedure, and it worked at creating the ISO, but still getting the same error messages about /dev/root does not exist.

@schakrava do you know when this UEFI iso will be released? I am not able to use my current hardware stably without UEFI, where as something is locking up with the regular BIOS iso. Thanks

**Comment by Lorgne** [comment]
@dbgunsolus: I extracted the content of the BIOS-only ISO in a ~/Rockstor-3.8-12/ folder and used these two commands to create a new ISO:

```
#!/bin/bash

mkisofs -U -A "Rockstor-3.8-12" -V "Rockstor 3 x86_64" \
    -volset "Rockstor-3.8-12" -J -joliet-long -r -v -T -x ./lost+found \
    -o ~/Rockstor-3.8-12-dualboot.iso \
    -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 \
    -boot-info-table -eltorito-alt-boot -e images/efiboot.img -no-emul-boot ~/Rockstor-3.8-12/

implantisomd5 ~/Rockstor-3.8-12-dualboot.iso
```

NB: 
- mkisofs needs to write to isolinux/isolinux.bin before the creation of the new ISO. A `chmod u+w isolinux.bin` was necessary in my case.
- The volume name under -V must be "Rockstor 3 x86_64" or your new ISO will not be recognized by the installer.
- A new MD5 must be implanted after creation of the ISO.

**Comment by dbgunsolus** [comment]
@Lorgne Thanks!! I tried the instructions and was able to create a iso again, but still saying 
/dev/root does not exist. Any idea why? And what are you using to write the disk to usb? Or are you mounting to the vm inside of HyperV? If you are just mounting it, what do you think would work to write it to a usb? Thanks

**Comment by dbgunsolus** [comment]
@Lorgne nvm, I rufus was causing it. Not sure what I would use besides it to make a UEFI iso. I have a Zalman that can mount ISO and emulate a cd/dvd drive and that did the trick to get into the installer, now I am having an issue under installation source, Error setting up base repository.

**Comment by schakrava** [comment]
Thank you @Lorgne! Sorry for the delayed merge, but your pr has been useful in my latest refactor as well.

**Pull request merged**
